import React,{useEffect,useLayoutEffect,useRef,useState} from 'react';
import {mapData} from './map-data.js';
const targets={overview:{x:5400,y:3875,w:5100},poseidon:{x:4500,y:3800,w:3000},jabali:{x:4550,y:5300,w:3000},caldera:{x:4500,y:3350,w:3000}};
export default function ProjectMap({t}){
 const bounds=useRef(null);const holder=useRef(null),drag=useRef(new Map()),gesture=useRef(null);const [svg,setSvg]=useState(''),[error,setError]=useState(false),[view,setView]=useState(targets.overview),[selected,setSelected]=useState('overview');
 useEffect(()=>{let live=true;(async()=>{try{const bytes=Uint8Array.from(atob(mapData),c=>c.charCodeAt(0));const decoded=await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).text();const doc=new DOMParser().parseFromString(decoded,'image/svg+xml');const node=doc.documentElement;node.querySelectorAll('script,foreignObject,image').forEach(n=>n.remove());node.querySelectorAll('*').forEach(n=>{for(const attr of [...n.attributes])if(/^on/i.test(attr.name))n.removeAttribute(attr.name);});node.removeAttribute('width');node.removeAttribute('height');node.setAttribute('width','100%');node.setAttribute('height','100%');if(live)setSvg(new XMLSerializer().serializeToString(node));}catch{if(live)setError(true)}})();return()=>{live=false}},[]);
 useLayoutEffect(()=>{const root=holder.current?.querySelector('svg');if(!root)return;const oldLogo=root.querySelector('#Layer_x0020_1');if(oldLogo){const b=oldLogo.getBBox();const logo=document.createElementNS('http://www.w3.org/2000/svg','image');logo.setAttribute('href','/grafton-logo.png');for(const [key,value] of Object.entries({x:b.x,y:b.y,width:b.width,height:b.height}))logo.setAttribute(key,String(value));logo.setAttribute('preserveAspectRatio','xMidYMid meet');oldLogo.replaceWith(logo);}const update=()=>{const {width,height}=holder.current.getBoundingClientRect();if(!bounds.current){const b=root.getBBox();bounds.current={x:b.x-120,y:b.y-120,w:b.width+240,h:b.height+240};}if(selected==='overview'){const b=bounds.current;root.setAttribute('viewBox',`${b.x} ${b.y} ${b.w} ${b.h}`);root.setAttribute('preserveAspectRatio','xMidYMid meet');}else{const h=view.w*height/width;root.setAttribute('viewBox',`${view.x-view.w/2} ${view.y-h/2} ${view.w} ${h}`);}};update();const ro=new ResizeObserver(update);ro.observe(holder.current);return()=>ro.disconnect();});
 useEffect(()=>{const node=holder.current;const wheel=e=>{if(!e.ctrlKey&&!e.metaKey)return;e.preventDefault();zoom(Math.exp(e.deltaY*.003));};node.addEventListener('wheel',wheel,{passive:false});return()=>node.removeEventListener('wheel',wheel);});
 const zoom=factor=>{const b=bounds.current;if(selected==='overview'&&b){const aspect=holder.current.clientWidth/holder.current.clientHeight;setView({x:b.x+b.w/2,y:b.y+b.h/2,w:Math.max(b.w,b.h*aspect)*factor});}else setView(v=>({...v,w:Math.max(900,Math.min(25000,v.w*factor))}));setSelected('');};
 const move=e=>{if(!drag.current.has(e.pointerId))return;const old=drag.current.get(e.pointerId);drag.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(drag.current.size===2){const [a,b]=[...drag.current.values()];const dist=Math.hypot(a.x-b.x,a.y-b.y);if(gesture.current)zoom(gesture.current/dist);gesture.current=dist;}else{const b=bounds.current;const fitted=selected==='overview'&&b?{x:b.x+b.w/2,y:b.y+b.h/2,w:Math.max(b.w,b.h*holder.current.clientWidth/holder.current.clientHeight)}:view;const scale=fitted.w/holder.current.clientWidth;setView({...fitted,x:fitted.x-(e.clientX-old.x)*scale,y:fitted.y-(e.clientY-old.y)*scale});}setSelected('');};
 const end=e=>{drag.current.delete(e.pointerId);gesture.current=null};
 return <div className="map-shell"><div className="map-toolbar"><div className="map-tabs">{Object.entries(targets).map(([key,value])=><button key={key} className={selected===key?'active':''} onClick={()=>{setSelected(key);setView(value)}}>{key==='overview'?t('Chile overview','Vista de Chile','智利概览'):key==='caldera'?'Caldera':key==='poseidon'?'Poseidon':'Jabalí'}</button>)}</div><span className="map-live"><i/>{t('EXPLORE THE PORTFOLIO','EXPLORAR LA CARTERA','探索项目组合')}</span></div><div className="map-area"><div ref={holder} className="original-map" role="application" aria-label={t('Project map. Use buttons to zoom and select a project.','Mapa de proyectos. Use los botones para navegar.','项目地图。使用按钮缩放和选择项目。')} tabIndex={0} onPointerDown={e=>{holder.current.setPointerCapture(e.pointerId);drag.current.set(e.pointerId,{x:e.clientX,y:e.clientY})}} onPointerMove={move} onPointerUp={end} onPointerCancel={end} onDoubleClick={()=>zoom(.7)} onKeyDown={e=>{if(['+','=','-','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))e.preventDefault();if(e.key==='+'||e.key==='=')zoom(.8);if(e.key==='-')zoom(1.25);const b=bounds.current;const v=selected==='overview'&&b?{x:b.x+b.w/2,y:b.y+b.h/2,w:Math.max(b.w,b.h*holder.current.clientWidth/holder.current.clientHeight)}:view;const delta=v.w*.08;if(e.key.startsWith('Arrow')){setView({...v,x:v.x+(e.key==='ArrowLeft'?-delta:e.key==='ArrowRight'?delta:0),y:v.y+(e.key==='ArrowUp'?-delta:e.key==='ArrowDown'?delta:0)});setSelected('');}}} dangerouslySetInnerHTML={{__html:svg}}/>{!svg&&<p className="map-loading">{error?t('Map unavailable. Please refresh.','Mapa no disponible. Actualice.','地图不可用，请刷新。'):t('Loading the project map…','Cargando el mapa…','正在加载项目地图…')}</p>}<div className="map-controls"><button aria-label={t('Zoom in','Acercar','放大')} onClick={()=>zoom(.75)}>+</button><button aria-label={t('Zoom out','Alejar','缩小')} onClick={()=>zoom(1.3)}>−</button><button aria-label={t('Reset map','Restablecer mapa','重置地图')} onClick={()=>{setView(targets.overview);setSelected('overview')}}>↺</button></div><div className="map-caption">{t('CHILE + ARGENTINA','CHILE + ARGENTINA','智利 + 阿根廷')}<span>W 70° / S 33°</span></div></div><div className="map-note"><span>{t('Drag to pan · Ctrl + scroll or pinch to zoom','Arrastre · Ctrl + rueda o pellizque para ampliar','拖动平移 · Ctrl + 滚轮或双指缩放')}</span><span>{t('Original wireframe map · Locations and ownership require company confirmation','Mapa original · Ubicaciones y propiedad por confirmar','原线框地图 · 位置和所有权有待公司确认')}</span></div></div>
}
